### PR TITLE
Coalesce Filter  update docs regarding pagination.

### PR DESCRIPTION
**Pull request by peec**
Disable pagination in example of Coalesce filter, see #144

### CODE REVIEW

**Comment by benkonrath** [comment]
Great that you found a solution to your problem. Why do you recommend setting `view.pagination_class = None` on every request instead of setting it on the specific View that you want to have the pagination disabled?

**Comment by peec** [comment]
ember-data will complain if it can't load related `ids[]`. So I think one would be better off handling this case at one place, as ember-data doesn't expect any pagination at all when trying to load records with given supplied `ids[]`. Pagination is only disabled when `ids[]` are supplied.

**Comment by benkonrath** [comment]
Ah ok, I understand. You want to be able to use the view as a regular paginated view and only disable pagination when it's an ember-data request with `ids[]`. Looks good to me.

@dustinfarris Any thoughts?

**Comment by dustinfarris** [comment]
I think this makes perfect sense.  I'm glad the solution is simple.  Thanks for sorting this out, @peec.

**Pull request merged**
