### PR TITLE
Update to 3.0. Fix tests by updating to ember-qunit RFC 232 & 268 style.

### LINKED ISSUE #212: Acceptance test fails because CRUD operation didn't finish up before app shutdown
The pull request https://github.com/dustinfarris/ember-django-adapter/pull/211 got rejected by acceptance test. The reason is that the test app shuts down before the save operation has finished his task. The fix for unit tests is described here:

https://github.com/danielspaniel/ember-data-factory-guy/issues/104

and here:

https://github.com/emberjs/guides/issues/909

### PR DESCRIPTION
**Pull request by benmurden**
In this update

- Run `ember-cli-upgrade --to=3.0`
- Run `ember-cli-upgrade --run-codemods`
- Modify acceptance tests to use `setupApplicationTest` and remove old `startApp` and `destroyApp` functions.
- Get store from `this.owner`.
- Modify `adapter:application` with `set` instead of overriding `subject` (which no longer exists).
- Update `ember-try` scenarios to latest LTS versions.
- Update Node requirements.

Resolves #212 and #210.

### CODE REVIEW

**Comment by benmurden** [comment]
Tests are noisy because of deprecations used in older `ember-data` versions. Could be remedied by including concomitant `ember-source` versions in `ember-try.js`.

**Comment by dustinfarris** [comment]
@oleroel would you mind reviewing this?

**Comment by OleRoel** [comment]
@dustinfarris @benmurden 

After going through the 25 files changed for a first time I couldn't find a thing that doesn't look correct to me. Although I've to admit that I don't know if some changes have been made by the `ember-cli-upgrade --run-codemods` command (e.g. in .eslintrc.js or testem.js). And I just cloned the [update-to-3.0](https://github.com/benmurden/ember-django-adapter/tree/update-to-3.0)  branch but didn't ran the tests nor did I try to use the repository in my own projects. I can offer to do this tomorrow (it's getting late here). But (again) I cannot guarantee to finish it, there are some other task on my plate for tomorrow.

**Comment by dustinfarris** [comment]
Thanks @OleRoel.  Please merge this when you are able to confirm that it works in your own project.

**Comment by OleRoel** [comment]
@dustinfarris @benmurden 
Status update: my other task took some time, I am going to review the code tomorrow. And please excuse the delay.

**Comment by OleRoel** [comment]
@dustinfarris @benmurden 
I just merged Ben's branch into master. Shouldn't we bump the tag? `v2.0.0.`is the latest.

**Comment by OleRoel** [comment]
@benmurden @dustinfarris 

Great, CircleCI fails with [here](https://circleci.com/gh/dustinfarris/ember-django-adapter/444) with

```
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_root/tornado
Storing debug log for failure in /home/ubuntu/.pip/pip.log

sudo pip install mkdocs returned exit code 1

Action failed: sudo pip install mkdocs
```

And before:
```
ImportError: Tornado requires an up-to-date SSL module. This means Python 2.7.9+ or 3.4+ (although some distributions have backported the necessary changes to older versions).
```

This looks to me like an issue that is not caused by the merged code.

And there is another warning in the head section:

```This project is currently running on CircleCI 1.0 which is no longer supported. Please start migrating this project to CircleCI 2.0.```

Uhm, I will do some research what might have caused the issue.

**Comment by dustinfarris** [comment]
Thanks for the hard work on this.  Will bump the version when CircleCI is happy (see #217).

**Comment by dustinfarris** [comment]
[v2.1.0 released](https://github.com/dustinfarris/ember-django-adapter/releases/tag/v2.1.0)

**Pull request merged**
