### PR TITLE
Switch back to rest serializer

### LINKED ISSUE #128: store.queryRecord error
I have something like this:

```
this.store.queryRecord('user', {email: 'myemail@gmail.com'}).then(function(user) {
  console.log(user);
});
```

The request is made successfully and I get an an array of one object back from django-rest-framework.
```
{"next":null,"previous":null,"results":[{"id":1,"email":"myemail@gmail.com","first_name":"test","last_name":"name"}]}
```
But I get this error:
```
Error: Assertion Failed: You must include an 'id' for user in an object passed to 'push'
```
Ember 1.13.5
Ember Data 1.13.7
EDA 1.0

### LINKED ISSUE #132: serializer.pushPayload is not a function
hello,

I am trying to push a record to the store that I get from a regular ajax callback.. tried using pushPayload but get `Uncaught TypeError: serializer.pushPayload is not a function`

any ideas why?

```
      request.done (response)=>
        response['id'] = response.username
        @store.pushPayload 'user', response
```

### PR DESCRIPTION
**Pull request by benkonrath**
This is ready to go. ~~except that I would like to get confirmation that this in fact fixes #132.~~

**Edit**: Let's deal with #132 separately.

Fixes #128 
Fixes #130

### CODE REVIEW

**Comment by erichonkanen** [comment]
@benkonrath 

```
_this.store.pushPayload('user', response)
store.js:1851 Uncaught TypeError: serializer.pushPayload is not a function
```

**Comment by erichonkanen** [comment]
`message: "Assertion Failed: You cannot use `store#pushPayload` without a modelName unless your default serializer defines `pushPayload`"`

**Comment by erichonkanen** [comment]
in console it does show `_this.store.pushPayload` so it may just be that Im not invoking it correctly (followed ember DS.store doc)..

**Comment by dustinfarris** [comment]
@erichonkanen try:

```js
let data = _this.store.normalize('user', response);
_this.store.pushPayload('user', data);
```

**Comment by rinti** [comment]
@benkonrath @dustinfarris I just ran in to (almost) the #128 problem, and this patch fixed it for me.

**Comment by dustinfarris** [comment]
@erichonkanen any update?

**Comment by benkonrath** [comment]
@dustinfarris Let's just deal with #132 separately if it still needs to be addressed.

**Comment by benkonrath** [comment]
@dustinfarris  What do you think about cutting a new release. Maybe 1.1?

**Pull request merged**
