### PR TITLE
Ember CLI Pagination integration

### PR DESCRIPTION
**Pull request by citmusa**
Documentation for integrating with Ember CLI Pagination addon

### CODE REVIEW

**Comment by dustinfarris** [comment]
Nice!  Thanks for putting this together!

**Comment by benkonrath** [comment]
@citmusa I wasn't able to get the pagination working with these instructions. Which version of Ember Django Adapter, Ember, Ember Data and Ember CLI Pagination worked for you? I'd like to add the version numbers to the documentation so people using different versions know they might have issues. Thanks.

**Comment by benkonrath** [comment]
@citmusa Scratch that. I just got it work. I didn't follow all of the steps from ember cli pagination. Thanks for your contribution.

**Comment by rinti** [comment]
This is almost exactly what I did to get Ember Infinity working, when I get to work I can see if there's any difference, Otherwise I might add some info about that too.

**Comment by benkonrath** [comment]
Yeah, that would be useful. In the meantime I've figured out that the custom pagination class is not required because you can calculate the total pages with the available information.

```js
import DRFSerializer from './drf';

export default DRFSerializer.extend({
  extractMeta: function(store, type, payload) {
    if (payload && payload.results) {
      // Sets the metadata for the type.s
      store.setMetadataFor(type, {
        count: payload.count,
        next: this.extractPageNumber(payload.next),
        previous: this.extractPageNumber(payload.previous),
        total_pages: Math.ceil(payload.count/payload.results.length)
      });

      // Keep ember data from trying to parse the metadata as a records
      delete payload.count;
      delete payload.next;
      delete payload.previous;
    }
  }
});
```

**Comment by benkonrath** [comment]
I updated the example to take some edge cases into account. I may make a PR for the docs with this example.

**Pull request merged**
