### PR TITLE
Update to ember-cli 0.2.4.

### LINKED ISSUE #79: Error on generated Adapter unit tests
I'm getting an error running unit tests for the DRF adapter and subclassed adapters.

See the following gist for an example:
https://gist.github.com/pkenway/9e77ca425d91fe925482

This is the error I get:
```

not ok 1 PhantomJS 1.9 - ApplicationAdapter: it exists
    ---
        actual: >
            null
        message: >
            beforeEach failed on it exists: 'undefined' is not a function (evaluating '(function () {
                  return ENV['default'].APP.API_HOST;
                }).property()')
        Log: >
    ...
ok 2 PhantomJS 1.9 - JSHint - unit/adapters: unit/adapters/application-test.js should pass jshint
```

This is with ember-cli 0.2.2.

Am I doing something wrong or is this a bug?

### PR DESCRIPTION
**Pull request by benkonrath**
Update to ember-cli 0.2.4 and fix #79

### CODE REVIEW

**Comment by benkonrath** [comment]
I've added ember-disable-prototype-extensions so that the issue can be solved in this PR. See the conversation about this in #79.

**Comment by benkonrath** [comment]
Ok, this is good to go. This also fixes #79.

**Comment by benkonrath** [comment]
This is worth a release bump in my opinion.

**Comment by holandes22** [comment]
Nice!

I agree with the release bump, which will also include #88

**Comment by dustinfarris** [comment]
Nice work.  Agree about the release bump—will get it out later today.

**Pull request merged**
