### PR TITLE
Revised Goals

### PR DESCRIPTION
**Pull request by dustinfarris**
Going to leave this open to comment for a few days.

/cc @benkonrath @holandes22

### CODE REVIEW

**Comment by benkonrath** [comment]
I originally wrote this to explain why I wanted to start from scratch instead of trying to continue with the old adapter. My personal goal for EDA is to ensure we continue to follow the officially supported way to create custom adapter in ED. I think the updated goals covers this and also solidifies the fact that we're interested in helping to fix issues in ED and in DRF if required.

I'm fine with this change. Thanks for taking the time to update this.

**Comment by holandes22** [comment]
Nice goals indeed. 

I really apologize guys I wasn't around to help, I was determined to help with this since I use it for personal projects, but my bandwidth got very limited lately due to work (unfortunately we don't use ember at work so wasn't able to squeeze work on EDA at my day job). I should be having more free time in 3 weeks, so I plan to help with any open issues to get ready for ED 1.0 release.

Being of course following, and just want to say that you did an amazing job on the implementation, tests and docs, kudos guys!

**Comment by dustinfarris** [comment]
Thanks, @holandes22!  No worries on the limited bandwidth—we can definitely sympathize with that!

**Comment by benkonrath** [comment]
@holandes22 Yeah, no problem on being busy - we appreciated your help in the beginning. :)

@dustinfarris Is this good to merge?

**Comment by dustinfarris** [comment]
@benkonrath yes, I think we're all in agreement.

**Pull request merged**
